//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanNuocHoa
{


    public partial class DSSanPham
    {
        protected global::System.Web.UI.WebControls.SqlDataSource srcSanPham;
        protected global::System.Web.UI.WebControls.ListView lstSanPham;

        protected global::System.Web.UI.WebControls.TextBox txtTuGia;
        protected global::System.Web.UI.WebControls.TextBox txtDenGia;
    }
}
