//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanNuocHoa
{


    public partial class ThemSanPham
    {
        protected global::System.Web.UI.WebControls.FileUpload upHinh;
        protected global::System.Web.UI.WebControls.TextBox txtTenSP;
        protected global::System.Web.UI.WebControls.TextBox txtGiaBan;
        protected global::System.Web.UI.WebControls.TextBox txtDungTich;
        protected global::System.Web.UI.WebControls.DropDownList drpLoaiSP;
        protected global::System.Web.UI.WebControls.Label lblThongBao;

    }
}
